### PR TITLE
Update API 8  and NET 7.0

### PR DESCRIPTION
**Pull request by 53m1k0l0n**
Update to API 8 and NET 7.0

### CODE REVIEW

**Comment by chrisk699** [comment]
Thank you for your contribution :-)

**Comment by 53m1k0l0n** [comment]
Are you maintaining it or is it cool if i take it and put it back in to Dalamud?
I mean by take it, complete i would, or tbh i have a own Repo of this.

**Comment by chrisk699** [comment]
I'm currently not maintaining this plugin anymore, but might come back to it in the future. I sent you an invitation to collaborate on this repo.

**Comment by 53m1k0l0n** [comment]
Well i think you don't know when you will maintain this again, the porblem is i can't PR it to Dalamud getting always Not your plugin, i think only the owner can pr it to dalamud. I mean i put you name in the Mainfest as owner, so i don't know what the porblem is, except, that i think, that only the onwer can do it. IDK if you have an idea.

**Pull request merged**
